branch-defaults:
  activeadminbugs:
    environment: Victoria-University
    group_suffix: null
global:
  application_name: Victoria University
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.5 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
