branch-defaults:
  master:
    environment: Victoria-University-env
    group_suffix: null
environment-defaults:
  Victoria-University-dev:
    branch: null
    repository: null
global:
  application_name: Victoria-University
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.5 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: https://github.com/Anthematics/Victoria-University
  sc: git
  workspace_type: Application
