development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: ‘aapj4uprkc3gl1.cnjcebityk2g.us-east-1.rds.amazonaws.com:5432’
# redis://redistogo:f9240a165777163e1e1c8c1c7cf97d7c@albacore.redistogo.com:10049/ Redis endpoint for heroku