---
development:
  adapter: postgresql
  database: victoria_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: "<%= ENV['RDS_DB_NAME'] %>"
  encoding: utf8
  host: "<%= ENV['RDS_HOSTNAME'] %>"
  password: "<%= ENV['RDS_PASSWORD'] %>"
  port: "<%= ENV['RDS_PORT'] %>"
  username: "<%= ENV['RDS_USERNAME'] %>"

test:
  adapter: postgresql
  database: victoria_test
  pool: 5
  timeout: 5000
