

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>
  publishable_key: 'pk_test_XvXaEOdYJkcmxoXIa3GzJHRB'
  secret_key: 'sk_test_1zCJsnkKnACw7fJggsPKECva'

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>
  publishable_key: 'pk_test_XvXaEOdYJkcmxoXIa3GzJHRB'
  secret_key: 'sk_test_1zCJsnkKnACw7fJggsPKECva'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>